/** Tags exibidas na nuvem 3D (rótulos curtos para legibilidade). */
export const SKILL_CLOUD_TAGS = [
  "React",
  "TypeScript",
  "Node.js",
  "Python",
  "AWS",
  "Flutter",
  "OpenCV",
  "PostgreSQL",
  "Docker",
  "IA",
  "Spring",
  "Redis",
  "Next.js",
  "OpenAI",
  "MongoDB",
  "Java",
  "CI/CD",
  "Azure",
  "GraphQL",
  "Kubernetes",
  "Whisper",
  "TDD",
] as const;
